### ISSUE TITLE
Query pagination: `total` field is always greater than results count by 1

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#2202]
## Repro

- Up Iroha: `docker compose up`
- Query to it with e.g. `FindAllDomains` & some great pagination limit such as `15`

## Expected output

Expected that `total` will be less than limit and equals to results count.

## Actual output

In YAML format:

```yaml
pagination:
  page: 1
  page_size: 15
  total: 3
data:
  - id: wonderland
    accounts:
      - id: alice@wonderland
        assets:
          - account_id: alice@wonderland
            definition_id: "rose#wonderland"
            value:
              t: Quantity
              c: 13
        metadata: {}
        roles: []
    logo: ~
    metadata: {}
    asset_definitions:
      - id: "rose#wonderland"
        value_type: Quantity
        mintable: Infinitely
    triggers: 0
  - id: genesis
    accounts:
      - id: genesis@genesis
        assets: []
        metadata: {}
        roles: []
    logo: ~
    metadata: {}
    asset_definitions: []
    triggers: 0
```
