### ISSUE TITLE
New peer sync failure

### ISSUE THREAD

**Issue by QuentinI** [hyperledger/iroha#2385]
### Summary
When registering a peer to an existing network it's able to join the network, but block synchronization fails with `validation failed error`

### Steps to reproduce:

Using the following `docker-compose.yml`:

<details>
<summary><code>docker-compose.yml</code></summary>
<br>

```yaml
version: "3.8"
services:
  iroha0:
    image: hyperledger/iroha2:dev
    environment:
      TORII_P2P_ADDR: iroha0:1337
      TORII_API_URL: iroha0:8080
      TORII_TELEMETRY_URL: iroha0:8180
      IROHA_PUBLIC_KEY: "ed01201c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"
      IROHA_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "282ed9f3cf92811c3818dbc4ae594ed59dc1a2f78e4241e31924e101d6b1fb831c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"}'
      SUMERAGI_TRUSTED_PEERS: '[{"address":"iroha0:1337", "public_key": "ed01201c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"}, {"address":"iroha1:1338", "public_key": "ed0120cc25624d62896d3a0bfd8940f928dc2abf27cc57cefeb442aa96d9081aae58a1"}, {"address": "iroha2:1339", "public_key": "ed0120faca9e8aa83225cb4d16d67f27dd4f93fc30ffa11adc1f5c88fd5495ecc91020"}]'
    ports:
      - "1337:1337"
      - "8080:8080"
      - "8180:8180"
    volumes:
      - './configs/peer:/config'
    init: true
    command: ./iroha --submit-genesis

  iroha1:
    image: hyperledger/iroha2:dev
    environment:
      TORII_P2P_ADDR: iroha1:1338
      TORII_API_URL: iroha1:8081
      TORII_TELEMETRY_URL: iroha1:8181
      IROHA_PUBLIC_KEY: "ed0120cc25624d62896d3a0bfd8940f928dc2abf27cc57cefeb442aa96d9081aae58a1"
      IROHA_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "3bac34cda9e3763fa069c1198312d1ec73b53023b8180c822ac355435edc4a24cc25624d62896d3a0bfd8940f928dc2abf27cc57cefeb442aa96d9081aae58a1"}'
      SUMERAGI_TRUSTED_PEERS: '[{"address":"iroha0:1337", "public_key": "ed01201c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"}, {"address":"iroha1:1338", "public_key": "ed0120cc25624d62896d3a0bfd8940f928dc2abf27cc57cefeb442aa96d9081aae58a1"}, {"address": "iroha2:1339", "public_key": "ed0120faca9e8aa83225cb4d16d67f27dd4f93fc30ffa11adc1f5c88fd5495ecc91020"}]'
    ports:
      - "1338:1338"
      - "8081:8081"
      - "8181:8181"
    volumes:
      - './configs/peer:/config'
    init: true

  iroha2:
    image: hyperledger/iroha2:dev
    environment:
      TORII_P2P_ADDR: iroha2:1339
      TORII_API_URL: iroha2:8082
      TORII_TELEMETRY_URL: iroha2:8182
      IROHA_PUBLIC_KEY: "ed0120faca9e8aa83225cb4d16d67f27dd4f93fc30ffa11adc1f5c88fd5495ecc91020"
      IROHA_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "1261a436d36779223d7d6cf20e8b644510e488e6a50bafd77a7485264d27197dfaca9e8aa83225cb4d16d67f27dd4f93fc30ffa11adc1f5c88fd5495ecc91020"}'
      SUMERAGI_TRUSTED_PEERS: '[{"address":"iroha0:1337", "public_key": "ed01201c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"}, {"address":"iroha1:1338", "public_key": "ed0120cc25624d62896d3a0bfd8940f928dc2abf27cc57cefeb442aa96d9081aae58a1"}, {"address": "iroha2:1339", "public_key": "ed0120faca9e8aa83225cb4d16d67f27dd4f93fc30ffa11adc1f5c88fd5495ecc91020"}]'
    ports:
      - "1339:1339"
      - "8082:8082"
      - "8182:8182"
    volumes:
      - './configs/peer:/config'
    init: true

  iroha3:
    image: hyperledger/iroha2:dev
    environment:
      TORII_P2P_ADDR: iroha3:1340
      TORII_API_URL: iroha3:8083
      TORII_TELEMETRY_URL: iroha3:8183
      IROHA_PUBLIC_KEY: "ed01208e351a70b6a603ed285d666b8d689b680865913ba03ce29fb7d13a166c4e7f1f"
      IROHA_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "a70dab95c7482eb9f159111b65947e482108cfe67df877bd8d3b9441a781c7c98e351a70b6a603ed285d666b8d689b680865913ba03ce29fb7d13a166c4e7f1f"}'
      SUMERAGI_TRUSTED_PEERS: '[{"address":"iroha0:1337", "public_key": "ed01201c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"}, {"address":"iroha1:1338", "public_key": "ed0120cc25624d62896d3a0bfd8940f928dc2abf27cc57cefeb442aa96d9081aae58a1"}, {"address": "iroha2:1339", "public_key": "ed0120faca9e8aa83225cb4d16d67f27dd4f93fc30ffa11adc1f5c88fd5495ecc91020"}]'
    ports:
      - "1340:1340"
      - "8083:8083"
      - "8183:8183"
    volumes:
      - './configs/peer:/config'
    init: true


```

</details>

Start the network

`docker-compose up iroha0 iroha1 iroha2`

Wait for genesis to be commited, then register new peer

`cargo run -p iroha_client_cli -- peer register --address '127.0.0.1:1340' --key ed01208e351a70b6a603ed285d666b8d689b680865913ba03ce29fb7d13a166c4e7f1f`

And then start the new peer

`docker-compose up iroha3`

<details>
<summary>Which produces the following output:</summary>
<br>
<img width="1512" alt="Screen Shot 2022-06-22 at 14 56 00" src="https://user-images.githubusercontent.com/18196237/175023336-72605bda-b2e1-4222-bcb1-c476e1074e30.png">

<details>
<summary>copyable</summary>
<br>

```
❯ docker-compose up iroha3
Recreating iroha_iroha3_1 ... done
Attaching to iroha_iroha3_1
iroha3_1  | 2022-06-22T11:05:29.106479Z  INFO iroha: Hyperledgerいろは2にようこそ！
iroha3_1  | 2022-06-22T11:05:29.108424Z  INFO iroha: (translation) Welcome to Hyperledger Iroha 2!
iroha3_1  | 2022-06-22T11:05:29.108741Z  INFO iroha: Starting peer listen_addr=iroha3:1340
iroha3_1  | 2022-06-22T11:05:29.109262Z  INFO iroha_p2p::network: Binding listener listen_addr=iroha3:1340
iroha3_1  | 2022-06-22T11:05:29.126901Z  INFO iroha_p2p::network: Starting network actor listen_addr=iroha3:1340
iroha3_1  | 2022-06-22T11:05:29.174566Z  INFO iroha_core::sumeragi::fault: Starting Sumeragi
iroha3_1  | 2022-06-22T11:05:29.180060Z  INFO iroha: Starting Iroha
iroha3_1  | 2022-06-22T11:05:29.180834Z  INFO iroha_core::sumeragi::fault: Connecting peer peer_to_be_connected.address=iroha0:1337
iroha3_1  | 2022-06-22T11:05:29.182460Z  INFO iroha_core::sumeragi::fault: Connecting peer peer_to_be_connected.address=iroha2:1339
iroha3_1  | 2022-06-22T11:05:29.182936Z  INFO iroha_core::sumeragi::fault: Connecting peer peer_to_be_connected.address=iroha1:1338
iroha3_1  | 2022-06-22T11:05:29.213352Z  INFO Server::run{addr=172.19.0.5:8183}: warp::server: listening on http://172.19.0.5:8183
iroha3_1  | 2022-06-22T11:05:29.213255Z  INFO Server::run{addr=172.19.0.5:8083}: warp::server: listening on http://172.19.0.5:8083
iroha3_1  | 2022-06-22T11:05:29.242170Z  INFO handle{self=Network { peers: 0 } msg=Connected(Id { address: "iroha0:1337", public_key: PublicKey { digest_function: Ed25519, payload: "1C61FAF8FE94E253B93114240394F79A607B7FA55F9E5A41EBEC74B88055768B" } }, 2231270440072095163)}: iroha_p2p::network: Peer connected listen_addr=iroha3:1340 count.new_peers=5 count.peers=1
iroha3_1  | 2022-06-22T11:05:29.242991Z  INFO handle{self=Network { peers: 1 } msg=Connected(Id { address: "iroha1:1338", public_key: PublicKey { digest_function: Ed25519, payload: "CC25624D62896D3A0BFD8940F928DC2ABF27CC57CEFEB442AA96D9081AAE58A1" } }, 96817922759028818)}: iroha_p2p::network: Peer connected listen_addr=iroha3:1340 count.new_peers=4 count.peers=2
iroha3_1  | 2022-06-22T11:05:29.243222Z  INFO handle{self=Network { peers: 2 } msg=Connected(Id { address: "172.19.0.2:45668", public_key: PublicKey { digest_function: Ed25519, payload: "CC25624D62896D3A0BFD8940F928DC2ABF27CC57CEFEB442AA96D9081AAE58A1" } }, 8480868454773946164)}: iroha_p2p::network: Peer connected listen_addr=iroha3:1340 count.new_peers=3 count.peers=2
iroha3_1  | 2022-06-22T11:05:29.243552Z  INFO handle{self=Network { peers: 2 } msg=Connected(Id { address: "iroha2:1339", public_key: PublicKey { digest_function: Ed25519, payload: "FACA9E8AA83225CB4D16D67F27DD4F93FC30FFA11ADC1F5C88FD5495ECC91020" } }, 4171030012129308009)}: iroha_p2p::network: Peer connected listen_addr=iroha3:1340 count.new_peers=2 count.peers=3
iroha3_1  | 2022-06-22T11:05:29.243693Z  INFO handle{self=Network { peers: 3 } msg=Connected(Id { address: "172.19.0.4:33504", public_key: PublicKey { digest_function: Ed25519, payload: "FACA9E8AA83225CB4D16D67F27DD4F93FC30FFA11ADC1F5C88FD5495ECC91020" } }, 5506693571672878753)}: iroha_p2p::network: Peer connected listen_addr=iroha3:1340 count.new_peers=1 count.peers=3
iroha3_1  | 2022-06-22T11:05:29.243774Z  INFO handle{self=Network { peers: 3 } msg=Connected(Id { address: "172.19.0.3:37922", public_key: PublicKey { digest_function: Ed25519, payload: "1C61FAF8FE94E253B93114240394F79A607B7FA55F9E5A41EBEC74B88055768B" } }, 17882832463664744258)}: iroha_p2p::network: Peer connected listen_addr=iroha3:1340 count.new_peers=0 count.peers=3
iroha3_1  | 2022-06-22T11:05:34.433164Z  WARN iroha_core::block_sync::message: Block hash not found hash=727582fe1123003cfe7aa511f1a46a436e459fecccd4d31fbde62a2c1d909548
iroha3_1  | 2022-06-22T11:05:39.238768Z  INFO iroha_core::block_sync: Synchronizing blocks blocks_left=2
iroha3_1  | 2022-06-22T11:05:39.240028Z  INFO iroha_core::sumeragi::fault: Using network topology from genesis block
iroha3_1  | 2022-06-22T11:05:39.267480Z  INFO commit_block: iroha_core::sumeragi::fault: Committing block prev_peer_role=ProxyTail new_peer_role=ProxyTail new_block_height=1 block_hash=0bca86cebc00ff2bcd4fd17b5714cb051461e6acd431b9df89d12f72284f4192
iroha3_1  | 2022-06-22T11:05:39.276588Z  INFO iroha_core::block_sync: Synchronizing blocks blocks_left=1
iroha3_1  | 2022-06-22T11:05:39.277751Z  WARN iroha_core::block_sync: Failed to commit a block received via synchronization request - validation failed block_hash=727582fe1123003cfe7aa511f1a46a436e459fecccd4d31fbde62a2c1d909548
```

</details>
</details>

### Possible reasons:

New peer fails [this](https://github.com/hyperledger/iroha/blob/43be45fc7fb7b0bd73f87b4fef167d61680c8e1e/core/src/block_sync.rs#L192) check, which means it's expecting topology which diverges from what the network thinks. As far as I can tell there shouldn't be any view changes happening there, so I'm at a loss as to why it would happen, especially since it successfully syncs some number of blocks before failing.
