### ISSUE TITLE
[BUG] Fault tolerance not working 7/0 peers.

### ISSUE THREAD

**Issue by astrokov7** [hyperledger/iroha#3084]
### OS and Environment

MacOS, Docker Hub

### GIT commit hash

ac35bda6

### Minimum working example / Steps to reproduce

1. Run the `docker-compose.yml` with 7 peers below.
```yml
version: "3.8"
services:
  iroha0:
    image: hyperledger/iroha2:dev
    environment:
      TORII_P2P_ADDR: iroha0:1337
      TORII_API_URL: iroha0:8080
      TORII_TELEMETRY_URL: iroha0:8180
      IROHA_PUBLIC_KEY: "ed01201c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"
      IROHA_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "282ed9f3cf92811c3818dbc4ae594ed59dc1a2f78e4241e31924e101d6b1fb831c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"}'
      SUMERAGI_TRUSTED_PEERS: '[{"address":"iroha0:1337", "public_key": "ed01201c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"}, {"address":"iroha1:1338", "public_key": "ed0120cc25624d62896d3a0bfd8940f928dc2abf27cc57cefeb442aa96d9081aae58a1"}, {"address": "iroha2:1339", "public_key": "ed0120faca9e8aa83225cb4d16d67f27dd4f93fc30ffa11adc1f5c88fd5495ecc91020"}, {"address": "iroha3:1340", "public_key": "ed01208e351a70b6a603ed285d666b8d689b680865913ba03ce29fb7d13a166c4e7f1f"}, {"address": "iroha4:1341", "public_key": "ed0120e23057aad8a49cb05028c16113306dca761a32f731ba2abde7d447ac9f5e347e"}, {"address": "iroha5:1342", "public_key": "ed012054b2008e5d71065ae061131eee052d282cdba7dc0363a3d87a91409ad91a1dda"}, {"address": "iroha6:1343", "public_key": "ed01201feeba0ba2238a5c63b7b9992c13da227c787e519a19c666de369c943ea876a8"}]'
      IROHA_GENESIS_ACCOUNT_PUBLIC_KEY: 'ed01203f4e3e98571b55514edc5ccf7e53ca7509d89b2868e62921180a6f57c2f4e255'
      IROHA_GENESIS_ACCOUNT_PRIVATE_KEY: '{ "digest_function": "ed25519", "payload": "038ae16b219da35aa036335ed0a43c28a2cc737150112c78a7b8034b9d99c9023f4e3e98571b55514edc5ccf7e53ca7509d89b2868e62921180a6f57c2f4e255" }'
    ports:
      - "1337:1337"
      - "8080:8080"
      - "8180:8180"
    volumes:
      - './configs/peer:/config'
    init: true
    command: iroha --submit-genesis

  iroha1:
    image: hyperledger/iroha2:dev
    environment:
      TORII_P2P_ADDR: iroha1:1338
      TORII_API_URL: iroha1:8081
      TORII_TELEMETRY_URL: iroha1:8181
      IROHA_PUBLIC_KEY: "ed0120cc25624d62896d3a0bfd8940f928dc2abf27cc57cefeb442aa96d9081aae58a1"
      IROHA_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "3bac34cda9e3763fa069c1198312d1ec73b53023b8180c822ac355435edc4a24cc25624d62896d3a0bfd8940f928dc2abf27cc57cefeb442aa96d9081aae58a1"}'
      SUMERAGI_TRUSTED_PEERS: '[{"address":"iroha0:1337", "public_key": "ed01201c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"}, {"address":"iroha1:1338", "public_key": "ed0120cc25624d62896d3a0bfd8940f928dc2abf27cc57cefeb442aa96d9081aae58a1"}, {"address": "iroha2:1339", "public_key": "ed0120faca9e8aa83225cb4d16d67f27dd4f93fc30ffa11adc1f5c88fd5495ecc91020"}, {"address": "iroha3:1340", "public_key": "ed01208e351a70b6a603ed285d666b8d689b680865913ba03ce29fb7d13a166c4e7f1f"}, {"address": "iroha4:1341", "public_key": "ed0120e23057aad8a49cb05028c16113306dca761a32f731ba2abde7d447ac9f5e347e"}, {"address": "iroha5:1342", "public_key": "ed012054b2008e5d71065ae061131eee052d282cdba7dc0363a3d87a91409ad91a1dda"}, {"address": "iroha6:1343", "public_key": "ed01201feeba0ba2238a5c63b7b9992c13da227c787e519a19c666de369c943ea876a8"}]'
      IROHA_GENESIS_ACCOUNT_PUBLIC_KEY: 'ed01203f4e3e98571b55514edc5ccf7e53ca7509d89b2868e62921180a6f57c2f4e255'
    ports:
      - "1338:1338"
      - "8081:8081"
      - "8181:8181"
    volumes:
      - './configs/peer:/config'
    init: true

  iroha2:
    image: hyperledger/iroha2:dev
    environment:
      TORII_P2P_ADDR: iroha2:1339
      TORII_API_URL: iroha2:8082
      TORII_TELEMETRY_URL: iroha2:8182
      IROHA_PUBLIC_KEY: "ed0120faca9e8aa83225cb4d16d67f27dd4f93fc30ffa11adc1f5c88fd5495ecc91020"
      IROHA_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "1261a436d36779223d7d6cf20e8b644510e488e6a50bafd77a7485264d27197dfaca9e8aa83225cb4d16d67f27dd4f93fc30ffa11adc1f5c88fd5495ecc91020"}'
      SUMERAGI_TRUSTED_PEERS: '[{"address":"iroha0:1337", "public_key": "ed01201c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"}, {"address":"iroha1:1338", "public_key": "ed0120cc25624d62896d3a0bfd8940f928dc2abf27cc57cefeb442aa96d9081aae58a1"}, {"address": "iroha2:1339", "public_key": "ed0120faca9e8aa83225cb4d16d67f27dd4f93fc30ffa11adc1f5c88fd5495ecc91020"}, {"address": "iroha3:1340", "public_key": "ed01208e351a70b6a603ed285d666b8d689b680865913ba03ce29fb7d13a166c4e7f1f"}, {"address": "iroha4:1341", "public_key": "ed0120e23057aad8a49cb05028c16113306dca761a32f731ba2abde7d447ac9f5e347e"}, {"address": "iroha5:1342", "public_key": "ed012054b2008e5d71065ae061131eee052d282cdba7dc0363a3d87a91409ad91a1dda"}, {"address": "iroha6:1343", "public_key": "ed01201feeba0ba2238a5c63b7b9992c13da227c787e519a19c666de369c943ea876a8"}]'
      IROHA_GENESIS_ACCOUNT_PUBLIC_KEY: 'ed01203f4e3e98571b55514edc5ccf7e53ca7509d89b2868e62921180a6f57c2f4e255'
    ports:
      - "1339:1339"
      - "8082:8082"
      - "8182:8182"
    volumes:
      - './configs/peer:/config'
    init: true

  iroha3:
    image: hyperledger/iroha2:dev
    environment:
      TORII_P2P_ADDR: iroha3:1340
      TORII_API_URL: iroha3:8083
      TORII_TELEMETRY_URL: iroha3:8183
      IROHA_PUBLIC_KEY: "ed01208e351a70b6a603ed285d666b8d689b680865913ba03ce29fb7d13a166c4e7f1f"
      IROHA_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "a70dab95c7482eb9f159111b65947e482108cfe67df877bd8d3b9441a781c7c98e351a70b6a603ed285d666b8d689b680865913ba03ce29fb7d13a166c4e7f1f"}'
      SUMERAGI_TRUSTED_PEERS: '[{"address":"iroha0:1337", "public_key": "ed01201c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"}, {"address":"iroha1:1338", "public_key": "ed0120cc25624d62896d3a0bfd8940f928dc2abf27cc57cefeb442aa96d9081aae58a1"}, {"address": "iroha2:1339", "public_key": "ed0120faca9e8aa83225cb4d16d67f27dd4f93fc30ffa11adc1f5c88fd5495ecc91020"}, {"address": "iroha3:1340", "public_key": "ed01208e351a70b6a603ed285d666b8d689b680865913ba03ce29fb7d13a166c4e7f1f"}, {"address": "iroha4:1341", "public_key": "ed0120e23057aad8a49cb05028c16113306dca761a32f731ba2abde7d447ac9f5e347e"}, {"address": "iroha5:1342", "public_key": "ed012054b2008e5d71065ae061131eee052d282cdba7dc0363a3d87a91409ad91a1dda"}, {"address": "iroha6:1343", "public_key": "ed01201feeba0ba2238a5c63b7b9992c13da227c787e519a19c666de369c943ea876a8"}]'
      IROHA_GENESIS_ACCOUNT_PUBLIC_KEY: 'ed01203f4e3e98571b55514edc5ccf7e53ca7509d89b2868e62921180a6f57c2f4e255'
    ports:
      - "1340:1340"
      - "8083:8083"
      - "8183:8183"
    volumes:
      - './configs/peer:/config'
    init: true

  iroha4:
    image: hyperledger/iroha2:dev
    environment:
      TORII_P2P_ADDR: iroha4:1341
      TORII_API_URL: iroha4:8084
      TORII_TELEMETRY_URL: iroha4:8184
      IROHA_PUBLIC_KEY: "ed0120e23057aad8a49cb05028c16113306dca761a32f731ba2abde7d447ac9f5e347e"
      IROHA_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "449dab240ceba408d21cb450cd3107ad80c7a3ee0e309fb84f9a91726ed4eb2fe23057aad8a49cb05028c16113306dca761a32f731ba2abde7d447ac9f5e347e"}'
      SUMERAGI_TRUSTED_PEERS: '[{"address":"iroha0:1337", "public_key": "ed01201c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"}, {"address":"iroha1:1338", "public_key": "ed0120cc25624d62896d3a0bfd8940f928dc2abf27cc57cefeb442aa96d9081aae58a1"}, {"address": "iroha2:1339", "public_key": "ed0120faca9e8aa83225cb4d16d67f27dd4f93fc30ffa11adc1f5c88fd5495ecc91020"}, {"address": "iroha3:1340", "public_key": "ed01208e351a70b6a603ed285d666b8d689b680865913ba03ce29fb7d13a166c4e7f1f"}, {"address": "iroha4:1341", "public_key": "ed0120e23057aad8a49cb05028c16113306dca761a32f731ba2abde7d447ac9f5e347e"}, {"address": "iroha5:1342", "public_key": "ed012054b2008e5d71065ae061131eee052d282cdba7dc0363a3d87a91409ad91a1dda"}, {"address": "iroha6:1343", "public_key": "ed01201feeba0ba2238a5c63b7b9992c13da227c787e519a19c666de369c943ea876a8"}]'
      IROHA_GENESIS_ACCOUNT_PUBLIC_KEY: 'ed01203f4e3e98571b55514edc5ccf7e53ca7509d89b2868e62921180a6f57c2f4e255'
    ports:
      - "1341:1341"
      - "8084:8084"
      - "8184:8184"
    volumes:
      - './configs/peer:/config'
    init: true

  iroha5:
    image: hyperledger/iroha2:dev
    environment:
      TORII_P2P_ADDR: iroha5:1342
      TORII_API_URL: iroha5:8095
      TORII_TELEMETRY_URL: iroha5:8195
      IROHA_PUBLIC_KEY: "ed012054b2008e5d71065ae061131eee052d282cdba7dc0363a3d87a91409ad91a1dda"
      IROHA_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "44643be1ddd3a679a2a092dc021ad34c0faa3e1df6b6d88f345057861d577d8954b2008e5d71065ae061131eee052d282cdba7dc0363a3d87a91409ad91a1dda"}'
      SUMERAGI_TRUSTED_PEERS: '[{"address":"iroha0:1337", "public_key": "ed01201c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"}, {"address":"iroha1:1338", "public_key": "ed0120cc25624d62896d3a0bfd8940f928dc2abf27cc57cefeb442aa96d9081aae58a1"}, {"address": "iroha2:1339", "public_key": "ed0120faca9e8aa83225cb4d16d67f27dd4f93fc30ffa11adc1f5c88fd5495ecc91020"}, {"address": "iroha3:1340", "public_key": "ed01208e351a70b6a603ed285d666b8d689b680865913ba03ce29fb7d13a166c4e7f1f"}, {"address": "iroha4:1341", "public_key": "ed0120e23057aad8a49cb05028c16113306dca761a32f731ba2abde7d447ac9f5e347e"}, {"address": "iroha5:1342", "public_key": "ed012054b2008e5d71065ae061131eee052d282cdba7dc0363a3d87a91409ad91a1dda"}, {"address": "iroha6:1343", "public_key": "ed01201feeba0ba2238a5c63b7b9992c13da227c787e519a19c666de369c943ea876a8"}]'
      IROHA_GENESIS_ACCOUNT_PUBLIC_KEY: 'ed01203f4e3e98571b55514edc5ccf7e53ca7509d89b2868e62921180a6f57c2f4e255'
    ports:
      - "1342:1342"
      - "8095:8095"
      - "8195:8195"
    volumes:
      - './configs/peer:/config'
    init: true

  iroha6:
    image: hyperledger/iroha2:dev
    environment:
      TORII_P2P_ADDR: iroha6:1343
      TORII_API_URL: iroha6:8086
      TORII_TELEMETRY_URL: iroha6:8186
      IROHA_PUBLIC_KEY: "ed01201feeba0ba2238a5c63b7b9992c13da227c787e519a19c666de369c943ea876a8"
      IROHA_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "c4e1e9ad5d21763375f81780d2d5ee0c4fc678d328c3f2517b511642f1382bfe1feeba0ba2238a5c63b7b9992c13da227c787e519a19c666de369c943ea876a8"}'
      SUMERAGI_TRUSTED_PEERS: '[{"address":"iroha0:1337", "public_key": "ed01201c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"}, {"address":"iroha1:1338", "public_key": "ed0120cc25624d62896d3a0bfd8940f928dc2abf27cc57cefeb442aa96d9081aae58a1"}, {"address": "iroha2:1339", "public_key": "ed0120faca9e8aa83225cb4d16d67f27dd4f93fc30ffa11adc1f5c88fd5495ecc91020"}, {"address": "iroha3:1340", "public_key": "ed01208e351a70b6a603ed285d666b8d689b680865913ba03ce29fb7d13a166c4e7f1f"}, {"address": "iroha4:1341", "public_key": "ed0120e23057aad8a49cb05028c16113306dca761a32f731ba2abde7d447ac9f5e347e"}, {"address": "iroha5:1342", "public_key": "ed012054b2008e5d71065ae061131eee052d282cdba7dc0363a3d87a91409ad91a1dda"}, {"address": "iroha6:1343", "public_key": "ed01201feeba0ba2238a5c63b7b9992c13da227c787e519a19c666de369c943ea876a8"}]'
      IROHA_GENESIS_ACCOUNT_PUBLIC_KEY: 'ed01203f4e3e98571b55514edc5ccf7e53ca7509d89b2868e62921180a6f57c2f4e255'
    ports:
      - "1343:1343"
      - "8086:8086"
      - "8186:8186"
    volumes:
      - './configs/peer:/config'
    init: true
```

2. Send transaction
```bash
./iroha_client_cli asset register \
    --id="tea#wonderland" \
    --value-type=Quantity
```

### Actual result

```bash
2023-01-25T12:49:22.822635Z ERROR iroha_core::sumeragi: This peer is faulty. Incoming messages have to be dropped due to low processing speed.
```

### Expected result

Successfully transaction

### Logs

<details>
  <summary>Log contents</summary>
  
  ```bash
2023-01-25T12:49:22.155425Z  WARN run: iroha_core::sumeragi::main_loop: No block produced in due time, requesting view change... role=ProxyTail
2023-01-25T12:49:22.181677Z  WARN iroha_p2p::network: Didn't find peer to send message peer.id=Id { address: "iroha5:1342", public_key: { digest: ed25519, payload: 54B2008E5D71065AE061131EEE052D282CDBA7DC0363A3D87A91409AD91A1DDA } }
2023-01-25T12:49:22.500266Z ERROR iroha_core::sumeragi: This peer is faulty. Incoming messages have to be dropped due to low processing speed.
2023-01-25T12:49:22.563178Z  WARN iroha_p2p::network: Unable to create peer error=Failed IO operation.
2023-01-25T12:49:22.563574Z  WARN iroha_p2p::network: Didn't find peer to send message peer.id=Id { address: "iroha5:1342", public_key: { digest: ed25519, payload: 54B2008E5D71065AE061131EEE052D282CDBA7DC0363A3D87A91409AD91A1DDA } }
2023-01-25T12:49:22.822635Z ERROR iroha_core::sumeragi: This peer is faulty. Incoming messages have to be dropped due to low processing speed.
2023-01-25T12:49:23.078555Z ERROR iroha_core::sumeragi: This peer is faulty. Incoming messages have to be dropped due to low processing speed.
2023-01-25T12:49:23.317350Z ERROR iroha_core::sumeragi: This peer is faulty. Incoming messages have to be dropped due to low processing speed.
2023-01-25T12:49:23.634494Z ERROR iroha_core::sumeragi: This peer is faulty. Incoming messages have to be dropped due to low processing speed.
2023-01-25T12:49:23.686324Z  WARN iroha_p2p::network: Unable to create peer error=Failed IO operation.
  ```
</details>

### Who can help to reproduce?

@astrokov7
