### ISSUE TITLE
[suggestion] Configure time-related values in a convenient way

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#3573]
### Feature request

Consider `queue.transaction_time_to_live_ms`. Currently user should specify the amount of milliseconds:

*Pseudoconfig:*

```toml
[queue]
transaction_time_to_live_ms = 86400000 # 24 hrs
```

It would be nice to be able to specify such a value in a more readable and convenient way. For example, the approach from [`ms` library](https://github.com/vercel/ms) could be used:

```toml
[queue]
transaction_time_to_live_ms = "24h"
```

Another forms like `3d`, `3 days`, `2 months`, `1h 5min` could be used.

### Motivation

The configuration format will be more declarative and easier to use.
