### ISSUE TITLE
Export data model through `iroha_client`

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4080]
## Description

At the moment the user has to import `iroha_data_model` directly in their `Cargo.toml`. What we should rather do is to export data model from `iroha_client`. Instead of having this:

```toml
[package]
name = "demo"

[dependencies]
iroha_client = {path = "../iroha/client/"}
iroha_data_model = {path = "../iroha/data_model/"}
```

```rs
use iroha_client::client::{Client, QueryResult};
use iroha_data_model::prelude::*;

fn main() {
    // some code
}
```

we should have this:

```toml
[package]
name = "demo"

[dependencies]
iroha_client = {path = "../iroha/client/"}
```

```rs
use iroha_client::{
    client::{Client, QueryResult}, 
    data_model::prelude::*
};

fn main() {
    // some code
}
```

## Benefits

By doing this we will gain more fine grained control over what API from `iroha_data_model` we want to expose to the user. The situation is such that `iroha_data_model` contains a lot of API that is relevant only to SDK devs and irrelevant/confusing for end users. This way we can filter what user has access to.

Also, this will make our API more consistent because we expose data model through `iroha_smart_contract::data_model`
