### ISSUE TITLE
[suggestion] (de-)serialize `PrivateKey` with `algorithm` field

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#4287]
`iroha_crypto::PrivateKey` serialized form contains `digest_function` and `payload` fields:

```toml
[private_key]
digest_function = "ed25519"
payload = "8f4c15e5d664da3f13778801d23d4e89b76e94c1b94b389544168b6cb894f84f8ba62848cf767d72e7f7f4b9d2d7ba07fee33760f79abe5597a51520e292a0cb"
```

I propose rename it to `algorithm`, to be concise and to reflect internal representation:

```toml
[private_key]
algorithm = "ed25519"
payload = "8f4c15e5d664da3f13778801d23d4e89b76e94c1b94b389544168b6cb894f84f8ba62848cf767d72e7f7f4b9d2d7ba07fee33760f79abe5597a51520e292a0cb"
```
