### ISSUE TITLE
[suggestion] Adopt multihash format for private keys

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#4412]
In configurations, we use the following format for public/private keys:

```toml
public_key = "ed012014A2900349A8CB6250D8CE5399D1964766B559A37F48E8C98C1EA83F365D8A72"
private_key = { algorithm = "ed25519", payload = "67AAB998A3951A071324B815BAF425309D6AF8D2D2636A3FC2BEA01C322BC23B14A2900349A8CB6250D8CE5399D1964766B559A37F48E8C98C1EA83F365D8A72" }
```

While multihash format is used for `public_key`, why can't we use it for the private one too?

It would make config more consistent and less confusing, and will also remove necessity to set private key in the environment through 2 split variables `PRIVATE_KEY_ALGORITHM` and `PRIVATE_KEY_PAYLOAD`.
