### ISSUE TITLE
Remove public key from private key

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4838]
It has been noted by @Erigara that we pack public key into private key. There doesn't seem to be any need for that, unless it's some sort of standard? This decision was probably inherited from ursa. It might have been done so that it's possible to generate public key from private key?

For example in `client.toml` we have:
```toml
[account]
domain = "wonderland"
public_key = "ed0120CE7FA46C9DCE7EA4B125E2E36BDB63EA33073E7590AC92816AE1E861B7048B03"
private_key = "802640CCF31D85E3B32A4BEA59987CE0C78E3B8E2DB93881468AB2435FE45D5C9DCD53CE7FA46C9DCE7EA4B125E2E36BDB63EA33073E7590AC92816AE1E861B7048B03"
```

let's simplify this and remove public key from private key
