### ISSUE TITLE
Can i launch the redis&postgres db inside the official hyperledger/iroha-docker:develop container

### ISSUE THREAD

**Issue by haojun** [hyperledger/iroha#892]
Hi, i'm setting up a test environment with 2 peers on a single machine. The composer file is as below. 
As you can see, now i need to start independent redis&postgres containers for each iroha peer. That can work but it starts too many containers. 
So I wonder whether hyperledger/iroha-docker:develop already has redis&postgres services? Can i launch those dbs within it, so i don't have to launch dbs outside? 
Any ideas? Thanks in advance.

```
version: '3'

services:
  iroha_node0:
    image: hyperledger/iroha-docker:develop
    container_name: iroha_node0
    ports:
      ...
    environment:
      ...
    depends_on:
      - iroha_redis0
      - iroha_pg0
    entrypoint: ["../wait-for-it.sh", "iroha_pg0:5432", "--", "irohad", "--genesis_block", "/opt/iroha/genesis.block", "--config", "/opt/iroha/node0/config.sample", "--keypair_name", "node0"]
    tty: true
    volumes:
      - ./:/opt/iroha
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/node0
    cap_add:
      - SYS_PTRACE

  iroha_node1:
    image: hyperledger/iroha-docker:develop
    container_name: iroha_node1
    ports:
      ...
    environment:
      ...
    depends_on:
      - iroha_redis1
      - iroha_pg1
    entrypoint: ["../wait-for-it.sh", "iroha_pg1:5432", "--", "irohad", "--genesis_block", "/opt/iroha/genesis.block", "--config", "/opt/iroha/node1/config.sample", "--keypair_name", "node1"]
    tty: true
    volumes:
      - ./:/opt/iroha
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/node1
    cap_add:
      - SYS_PTRACE

  iroha_redis0:
    image: redis:3.2.8
    container_name: iroha_redis0

  iroha_pg0:
    image: postgres:9.5
    container_name: iroha_pg0
    environment:
      - POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld

  iroha_redis1:
    image: redis:3.2.8
    container_name: iroha_redis1

  iroha_pg1:
    image: postgres:9.5
    container_name: iroha_pg1
    environment:
      - POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld

volumes:
  ccache-data:
```
